### ISSUE TITLE
Config for Gradle 6.4 +

### ISSUE THREAD

**Issue by pazz** [cs125-illinois/gradlegrader#2]
Hello!

Any chance you could add some documentation or demo config for a more recent gradle version?
Apparently, the [way to apply plugins has changed](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block) and I don't seem to be able to apply yours.
Apologies for the noob question. I am not really a Java developer.

Here is what I tried:

`build.gradle`:
```
plugins {
	id 'java'
        id 'application'
        id 'checkstyle'
        id 'edu.illinois.cs.cs125.gradlegrader' version '2020.1.0'
}

repositories {
	mavenCentral()
}

dependencies {
	testImplementation('org.junit.jupiter:junit-jupiter:5.6.0')
	testImplementation('com.github.cs125-illinois:gradlegrader:2020.1.0')
}
...
```

```terminal

./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/pazz/repo/teaching/2021-COMP122/templates/Assignment/build.gradle' line: 5

* What went wrong:
Plugin [id: 'edu.illinois.cs.cs125.gradlegrader', version: '2020.1.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'edu.illinois.cs.cs125.gradlegrader:edu.illinois.cs.cs125.gradlegrader.gradle.plugin:2020.1.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

```

Is it possible that there are several "mavenCentral" repositories?

**Comment by pazz** [comment]
This plugin does not exist here <https://repo1.maven.org/maven2/edu/illinois/cs/>
but is listed here <https://mvnrepository.com/artifact/com.github.cs125-illinois/gradlegrader>. Is this not the same "service" ?

**Comment by pazz** [comment]
In any case, a full example including full `build.gradle` and a complete test file would be much appreciated.

**Comment by Fleex255** [comment]
The classic `apply plugin` directive still works on new Gradle versions for Groovy (as opposed to Kotlin) buildscripts. If you are writing Kotlin buildscripts or would like to use the new `plugins` block, you will need to change the settings script (`settings.gradle` or `settings.gradle.kts`) to tell Gradle [where to find our plugin artifact](https://repo1.maven.org/maven2/com/github/cs125-illinois/gradlegrader/). Conveniently, this is valid as both Groovy and Kotlin code:

```kotlin
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.namespace == "edu.illinois.cs.cs125" && requested.version != null) {
                useModule("com.github.cs125-illinois:${requested.id.name}:${requested.version}")
            }
        }
    }
}
```

Once that's done, you can apply the plugin in the buildscript exactly as you had tried:

```groovy
plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'edu.illinois.cs.cs125.gradlegrader' version '2020.1.0'
}
```

**Comment by pazz** [comment]
beautiful, thanks!
I'm really looking forward to using gradlegrader for my module next year :)
